language: ruby
services: postgresql
before_script:
  - sudo apt-get install postgresql-contrib -qq -y
  - psql -c "CREATE USER rdo WITH PASSWORD 'rdo';" -U postgres
  - psql -c "CREATE DATABASE rdo WITH OWNER rdo;" -U postgres
script: "CONNECTION=postgres://rdo:rdo@127.0.0.1/rdo?encoding=utf-8 bundle exec rake spec"
rvm:
  - 1.9.2
  - 1.9.3
  - rbx-19mode
notifications:
  email: chris@w3style.co.uk
